export interface ITile {
  tileTitle: string;
  tileUrlPath: string;
  tileImagePath: string;
  tileDescription: string;
}

export const homeTiles: ITile[] = [
  {
    tileTitle: "Telemetry analyzer",
    tileDescription:
      "This tool is used to view, analyze, and compare telemetry files generated by Richard Burns Rally. Multiple file input is supported, so you can compare two different runs. ",
    tileImagePath: "telemetry.png",
    tileUrlPath: "/telemetry",
  },
  {
    tileTitle: "Setup Extractor",
    tileDescription:
      "This tool allows you to extract car setups from replay files. RBR's .rpl files are supported. You can preview extacted values, or save whole setup to your hard drive (default location is the download folder)",
    tileImagePath: "setup.png",
    tileUrlPath: "/extractor",
  },
  {
    tileTitle: "Setup Replacer",
    tileDescription:
      "Setup replacer can replace setup located in replay file, with another setup you provide. This way you can send your .rpl file without fear that your top secret suspension setting will be extracted by other people ;)",
    tileImagePath: "replacer.png",
    tileUrlPath: "/replacer",
  },
];
